[package]
name = "wasm-benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.32.5"
rustfft = "6.2.0"
wasm-bindgen = "0.2.92"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = 2
lto = "fat"
